### ISSUE TITLE
Add showcase project

### ISSUE THREAD

**Issue by ausov** [kradio3/react-mdc-web#1]
As user, I want to download an example showcase project so that I can see how I can use the library in my own projects.

Additionally, would be interesting to see: 

* how to apply theming
* how to re-use SASS (mixins/vars/etc) from the mdc
* generally, a simple showcase of components, if possible

Thank you in advance!

**Comment by kradio3** [comment]
* Theming described [here](https://github.com/kradio3/react-mdc-web/blob/master/docs/pages/theming/index.md)
* Components usage see on the [documentation site](https://kradio3.github.io/react-mdc-web/)
* Small showcase project could be cloned from [here](https://github.com/kradio3/react-mdc-web-showcase)

**Comment by ausov** [comment]
seems all there already. shall we close the issue?

**Comment by kradio3** [comment]
Yes, let's close it :)
