### ISSUE TITLE
Implement typography

### ISSUE THREAD

**Issue by foureggs** [kradio3/react-mdc-web#18]
It turns out that I was working on the exact same library. Even the coding and syntax conventions were almost identical. If you want to have a look, here is my implementation of mdc-typography.

```jsx
import React, { Component, PropTypes } from 'react';
import classnames from 'classnames';

class Typography extends Component {
  static propTypes = {
    className: PropTypes.string,
    tag: PropTypes.string,
    display4: PropTypes.bool,
    display3: PropTypes.bool,
    display2: PropTypes.bool,
    display1: PropTypes.bool,
    headline: PropTypes.bool,
    subheading2: PropTypes.bool,
    subheading1: PropTypes.bool,
    body2: PropTypes.bool,
    body1: PropTypes.bool,
    caption: PropTypes.bool
  }

  static defaultProps = {
    tag: 'h1'
  }

  get className() {
    const propClassNames = ['display4', 'display3', 'display2', 'display1', 'headline', 'subheading2', 'subheading1', 'body2', 'body1', 'caption'];
    return propClassNames
      .map(className => ({
        ['mdc-typography--'+className]: this.props[className]
      }))
      .reduce((prev, curr) => ({...prev, ...curr}), {});
  }

  render() {
    const {tag, className, ...otherProps} = this.props;
    return (
      <this.props.tag
        className={classnames(this.className, className)}
        {...otherProps}
      >
      </this.props.tag>
    );
  }
}

export default Typography;

```
![2017-04-08 12_56_19-react app](https://cloud.githubusercontent.com/assets/22561997/24828799/9e9a4cc2-1c5d-11e7-8503-8afa0f3368d8.png)
![2017-04-08 13_17_30-app js - react-materialed - visual studio code](https://cloud.githubusercontent.com/assets/22561997/24828806/c2dbe9b0-1c5d-11e7-8f1d-deaa27fe3c40.png)

**Comment by foureggs** [comment]
I was going to submit this as a PR, but I couldn't manage to get it working. Probably due to the fact that I am currently using a windows desktop and the scripts are designed to run on MacOS / linux.

**Comment by kradio3** [comment]
Hi @foreggs , thank you for contribution!
Looks that problem on Windows was with ```rm -rf```. I have changed it to cross-platform ```rimraf```
And also i can't understand how adjustMargin works. I've tried sth like this:
```javascript
  get className() {
    const propClassNames = [
      'adjust-margin',
      'body1',
      'body2',
```
And then
```jsx
<Typography display2 adjust-margin>Display2</Typography>
```
But on your picture ```adjustMargin``` :)
