### ISSUE TITLE
Remove css require in Menu

### ISSUE THREAD

**Issue by parsadotsh** [kradio3/react-mdc-web#21]
Some configurations can't require("*.css"). The only files with this are Menu/index.js and defaultTheme.js. I deleted that line and there doesn't seem to be any problem. Maybe we can remove it?

**Comment by kradio3** [comment]
Sure, i've removed it. Thanks @hyperparsa .

**Comment by kradio3** [comment]
Do you want to remove it from defaultTheme.js also? If your configuration doesn't support it just don't use defaultTheme.js
