### ISSUE TITLE
Module not found: Error: Can't resolve '@material/menu/dist/mdc.menu.min.css' in '*/node_modules/react-mdc-web/lib/Menu'

### ISSUE THREAD

**Issue by jhjaggars** [kradio3/react-mdc-web#23]
I ran into this error while following the examples from the README. I worked around the problem by changing the line in `lib/Menu/index.js` from

```javascript
require('@material/menu/dist/mdc.menu.min.css');
```

to

```javascript
require('material-components-web/dist/material-components-web.min.css');
```

I'm pretty sure this isn't the right thing to do (I'm very new at this). Does react-mdc-web need to add `@material` to its dependencies?

I've put up a reproducer at https://github.com/jhjaggars/react-mdc-web-repro.

**Comment by kradio3** [comment]
Hi @jhjaggars , this issue is fixed in #21 .
