### ISSUE TITLE
Implement Linear progres

### ISSUE THREAD

**Issue by piotr-cz** [kradio3/react-mdc-web#25]
docs: https://material.io/components/web/catalog/linear-progress/
source: https://github.com/material-components/material-components-web/tree/master/packages/mdc-linear-progress

Available since `material-components-web v0.12.0`

**Comment by kradio3** [comment]
Thanks. Progress is in progress :)

**Comment by piotr-cz** [comment]
Implemented in [v0.13.0](https://github.com/kradio3/react-mdc-web/tree/v0.13.0/src/LinearProgress)
