### ISSUE TITLE
CardTitle unconditionally uses the mdc-card__title--large style

### ISSUE THREAD

**Issue by ivmarkov** [kradio3/react-mdc-web#29]
`mdc-card__title--large` is described [here](https://github.com/material-components/material-components-web/tree/master/packages/mdc-card) as:

> `mdc-card__title--large`	An option for the title, to make it larger.

Well, I want to have the flexibility to *not* make it larger.  I think this deserves a property in the CardTitle props object.

**Comment by kradio3** [comment]
Hi, @ivmarkov , 
Thank you, fixed.

**Comment by ivmarkov** [comment]
That was fast - thank *you*
