### ISSUE TITLE
Grid / Cells don't seem to behave as expected

### ISSUE THREAD

**Issue by zer0tonin** [kradio3/react-mdc-web#30]
I would expect this two components to lead to the same results : 
[code using react-mdc-web](https://gist.github.com/zer0tonin/21eae8310e06929bbf2cdaad92575e4c)
[code using mdc classes](https://gist.github.com/zer0tonin/d2f52cb40dfbb908e0f4befd1c79c842)

However in practice the code using react-mdc-web just puts everything vertically ([screenshot](http://i.imgur.com/K0o5zpw.png)), while code using mdc classes work as expected, the elements are placed horizontally  ([screenshot](http://i.imgur.com/UttFayf.png)).

**Comment by kradio3** [comment]
Hi @zer0tonin ,
Grids are fixed in this commit 5d691c0 
It will be released asap
Thanks!
