### ISSUE TITLE
Halo doesn't disappear after click switch.

### ISSUE THREAD

**Issue by eromoe** [kradio3/react-mdc-web#37]
For example:

![image](https://user-images.githubusercontent.com/3938751/29303480-c79a15d6-81bf-11e7-8080-de7e223a3d98.png)
![image](https://user-images.githubusercontent.com/3938751/29303508-f4f83012-81bf-11e7-9878-c276b4bbad43.png)

Need click at other place to make halo disappear:
![image](https://user-images.githubusercontent.com/3938751/29303500-e3286da2-81bf-11e7-82fa-848ec48f9af8.png)

Can reproduce on (chrome 60)
https://kradio3.github.io/react-mdc-web/components/switch/

**Comment by kradio3** [comment]
i think it's not a bug. Because google's implementation has the same behavior. Have a look this demo https://material-components-web.appspot.com/switch.html
