### ISSUE TITLE
Update sample import in https://kradio3.github.io/react-mdc-web/

### ISSUE THREAD

**Issue by ataliadvanstep** [kradio3/react-mdc-web#45]
in documentation from your website, the sample to import react-mdc-web is incorrect

in your [home](https://kradio3.github.io/react-mdc-web/)

bug on this ligne
`import {Card, CardHeader, CardTitle} from 'react-mdc-web';`

should be : 
`import {Card, CardHeader, CardTitle} from 'react-mdc-web/lib';`

**Comment by kradio3** [comment]
Thank you, fixed
