### ISSUE TITLE
Change themes

### ISSUE THREAD

**Issue by mmayla** [kradio3/react-mdc-web#5]
I've read this about theming in MDC:
https://github.com/material-components/material-components-web/blob/master/docs/theming.md#step-3-changing-the-theme-with-sass

I want to change the whole application style, how can I do that using this project?

**Comment by bw2012** [comment]
as far as I know unfortunately it is not implemented at this moment
may be @kradio3 has private branch with this feature but it is not finished yet

**Comment by kradio3** [comment]
Yes, at the moment it's not implemented. But we'll solve it in next release. Approximately - until the end of this week. Thank you for paying attention

**Comment by kradio3** [comment]
### Current implementation:
At the moment we export components with default MDC style:
```js
// Toolbar/index.js
import '@material/toolbar/dist/mdc.toolbar.css';

export { default as Toolbar } from './Toolbar';
export { default as ToolbarSection } from './ToolbarSection';
export { default as ToolbarTitle } from './ToolbarTitle';
```

### Possible solution:
- To export components without any css by default:
  ```js
  // Toolbar/index.js
  export { default as Toolbar } from './Toolbar';
  export { default as ToolbarSection } from './ToolbarSection';
  export { default as ToolbarTitle } from './ToolbarTitle';
  ```
- Export component with default MDC style in separate file:
  ```js
  // Toolbar/styled.js
  import '@material/toolbar/dist/mdc.toolbar.css';
  export * from './';
  ```

Users who want to make some drafts with default styling will import components in this way:
```js
import { Toobar, ToolbarSection } from 'react-mdc-web/lib/Toolbar/styled';
```

And users who want to override default theme:
```js
// myTheme/toolbar.js
import 'toolbar.css';
export * from 'react-mdc-web/lib/Toolbar';

//App.js
import { Toolbar, ToolbarSection } from 'myTheme/toolbar';
```
@IJMacD , @MMayla , @bw2012 , @ausov , what you think about this solution?

**Comment by kradio3** [comment]
i've updated README.md and documentation site with theming guides

**Comment by cayasso** [comment]
Smart move removing the import styles!!!!!

**Comment by prakharrke** [comment]
Why does my content hide behind the Toolbar?
