### ISSUE TITLE
Icon inside a textfield

### ISSUE THREAD

**Issue by ataliadvanstep** [kradio3/react-mdc-web#50]
Hello,

I try to set an icon inside a textfield

In the material-components-web com official documentation, it's supported but how to do it with react-mdc-web ?
https://github.com/material-components/material-components-web/blob/master/demos/textfield.html

The code below do the job
`
          <div id="tf-box-leading-example"
            class="mdc-textfield mdc-textfield--box mdc-textfield--with-leading-icon" data-demo-no-auto-js>
            <i class="material-icons mdc-textfield__icon" tabindex="0">event</i>
            <input type="text" id="tf-box-leading" class="mdc-textfield__input custom-textfield-input">
            <label for="tf-box-leading" class="mdc-textfield__label">Your name</label>
            <div class="mdc-textfield__bottom-line"></div>
          </div>
`

**Comment by kradio3** [comment]
Hi @ataliadvanstep , sorry it wasn't implemented. Will be available in next release in few days

**Comment by ataliadvanstep** [comment]
cool !! waiting for it :-)



‌

**Comment by kradio3** [comment]
Released 
https://kradio3.github.io/react-mdc-web/components/text_field/
